clean up, add -Srepro, use different cache root for repro mode

diff --git a/src/main/resources/clojure b/src/main/resources/clojure
--- a/src/main/resources/clojure
+++ b/src/main/resources/clojure
@@ -4,7 +4,11 @@
 
 set -e
 
-# Extract java opts
+# Extract opts
+print_classpath=false
+verbose=false
+force=false
+repro=false
 java_opts=()
 while [ $# -gt 0 ]
 do
@@ -13,19 +17,6 @@ do
       java_opts+=("${1:2}")
       shift
       ;;
-    *)
-      break
-      ;;
-  esac
-done
-
-# Extract classpath opts
-show_classpath=false
-verbose=false
-force=false
-while [ $# -gt 0 ]
-do
-  case "$1" in
     -R*)
       resolve_aliases="${1:2}"
       shift
@@ -35,7 +26,7 @@ do
       shift
       ;;
     -Spath)
-      show_classpath=true
+      print_classpath=true
       shift
       ;;
     -Sverbose)
@@ -45,6 +36,14 @@ do
     -Sforce)
       force=true
       shift
+      ;;
+    -Srepro)
+      repro=true
+      shift
+      ;;
+    -S*)
+      echo "Invalid option:" $1
+      exit 1
       ;;
     *)
       break
@@ -83,8 +82,12 @@ else
   user_cache_dir="$config_dir/.cpcache"
 fi
 
-# Include install and config deps.edn in config paths
-config_paths=("$install_dir/deps.edn" "$config_dir/deps.edn" "deps.edn")
+# Chain deps.edn in config paths. repro=use only local.
+if "$repro"; then
+  config_paths=("deps.edn")
+else
+  config_paths=("$install_dir/deps.edn" "$config_dir/deps.edn" "deps.edn")
+fi
 
 # Determine whether to use user or project cache
 if [[ -f deps.edn ]]; then
@@ -94,13 +97,17 @@ else
 fi
 
 # Construct location of cached classpath file
-if [[ -n "$resolve_aliases" ]]; then
-  libs_root="$cache_dir/$resolve_aliases"
+if "$repro"; then
+  cache_root="$cache_dir/repro"
 else
-  libs_root="$cache_dir/default"
+  cache_root="$cache_dir"
+fi
+if [[ -n "$resolve_aliases" ]]; then
+  libs_root="$cache_root/$resolve_aliases"
+else
+  libs_root="$cache_root/default"
 fi
 libs_file="$libs_root.libs"
-
 if [[ -n "$classpath_aliases" ]]; then
   cp_file="$libs_root/$classpath_aliases.cp"
 else
@@ -109,16 +116,16 @@ fi
 
 # Print paths in verbose mode
 if "$verbose"; then
-  echo "install_dir = $install_dir"
-  echo "config_dir  = $config_dir"
-  echo "cache_dir   = $cache_dir"
-  echo "libs_file   = $libs_file"
-  echo "cp_file     = $cp_file"
+  echo "install_dir  = $install_dir"
+  echo "config_dir   = $config_dir"
+  echo "config_paths =" "${config_paths[@]}"
+  echo "cache_dir    = $cache_dir"
+  echo "cp_file      = $cp_file"
 fi
 
 # Check for stale classpath file
 stale=false
-if "$force" || [ ! -f "$cp_file" ] || [ ! -f "$libs_file" ] || [ "$libs_file" -nt "$cp_file" ]; then
+if "$force" || [ ! -f "$cp_file" ]; then
   stale=true
 else
   for config_path in "${config_paths[@]}"; do
@@ -132,7 +139,7 @@ fi
 # If stale, run makecp to refresh cached classpath
 if "$stale"; then
   if "$verbose"; then
-    echo "cp_file is stale"
+    echo "Refreshing classpath"
   fi
   tools_cp="$install_dir/libexec/clojure-scripts-${project.version}.jar"
   tools_args=()
@@ -146,12 +153,12 @@ if "$stale"; then
 
   config_str=$(printf ",%s" "${config_paths[@]}")
   config_str=${config_str:1}
-  "$JAVA_CMD" -Xmx256m -classpath "$tools_cp" clojure.main -m clojure.tools.deps.alpha.makecp "--config-paths=$config_str" "--cache-path=$cache_dir" "${tools_args[@]}"
+  "$JAVA_CMD" -Xmx256m -classpath "$tools_cp" clojure.main -m clojure.tools.deps.alpha.makecp "--config-paths=$config_str" "--libs-file=$libs_file" "--cp-file=$cp_file" "${tools_args[@]}"
 fi
 
 cp=$(cat "$cp_file")
 
-if "$show_classpath"; then
+if "$print_classpath"; then
   echo "$cp"
 else
   "$JAVA_CMD" "${java_opts[@]}" -classpath "$cp" clojure.main "$@"
